### ISSUE TITLE
0x750E - wrong packet description

### ISSUE THREAD

**Issue by mxii** [DummkopfOfHachtenduden/SilkroadDoc#1]
Hey,

I saw this: 0x750E - CLIENT_AGENT_ENVIRONMENT_WEATHER_REQUEST.cs

Thats not correct. :)
This opcode is for requesting your consignment list.

This packet is normally send by the client directly after the "spawn confirmation" (0x3012).
If you are clientless you have to send this packet manually.

Response (0xB50E):

uint8 itemCount;
uint32 consignmentId
uint8 consignmentState (0 = registered, 1 = sold, 2 = expired)
uint32 itemModelid (see itemdata..)
uint16 quantity
uint8[2] unknown .. (maybe quantity is 4 bytes long?!)
uint64 registered price
uint64 deposit price
uint64 comission price
uint32 seconds (till 1.1.1970.. presents the expiration-date or "item will be deleted"-date if already expired!)

**Comment by DummkopfOfHachtenduden** [comment]
Thanks for pointing out, issue has been resolved.

That must've been a left over from prior assumptions I made and thus creating a duplicate.
0x750E and 0xB50E where already correctly listed under [consignment in wiki.](https://github.com/DummkopfOfHachtenduden/SilkroadDoc/wiki/Agent-packets#consignment)

`0x750E - CLIENT_AGENT_CONSIGNMENT_LIST_REQUEST.cs`

``` csharp
//Empty
```

`0xB50E - SERVER_AGENT_CONSIGNMENT_LIST_RESPONSE.cs`

``` csharp
1   byte    result
if(result == 1)
{
    1   byte    itemCount
    foreach(item)
    {
        4   uint    PersonalID
        1   byte    Status    //ConsignmentSaleStatus.cs
        4   uint    RefItemID
        4   uint    SellCnt
        8   ulong   Price
        8   ulong   Deposit
        8   ulong   SellFee
        4   uint    EndDate //as epoch
    }
}
else if(result == 2)
{
    2   ushort  errorCode
}
```

**Comment by mxii** [comment]
Ok, nice!

But your "TidGroupID" ist definitly the quantity.. See an live-example:

01
10 // 16 items
03 02 00 00
00
5F 0E 00 00
E8 03 00 00 // stack of 1000 elixirs :)
00 65 CD 1D 00 00 00 00
40 78 7D 01 00 00 00 00
80 F0 FA 02 00 00 00 00
14 08 5F 57

06 02 00 00
00
3A 99 00 00
01 00 00 00
01 CA 9A 3B 00 00 00 00
80 F0 FA 02 00 00 00 00
00 E1 F5 05 00 00 00 00
14 08 5F 57

FF 01 00 00
01
74 98 00 00
01 00 00 00
02 CA 9A 3B 00 00 00 00
80 F0 FA 02 00 00 00 00
00 E1 F5 05 00 00 00 00
04 CC 7D 57

00 02 00 00
01
0A 99 00 00
01 00 00 00
01 CA 9A 3B 00 00 00 00
80 F0 FA 02 00 00 00 00
00 E1 F5 05 00 00 00 00
2C 3A 7E 57

01 02 00 00
01
55 99 00 00
01 00 00 00
00 CA 9A 3B 00 00 00 00
80 F0 FA 02 00 00 00 00
00 E1 F5 05 00 00 00 00
00 EE 7D 57

F9 01 00 00
01
C8 98 00 00
01 00 00 00
00 CA 9A 3B 00 00 00 00
80 F0 FA 02 00 00 00 00
00 E1 F5 05 00 00 00 00
90 4D 7F 57

02 02 00 00
01
1F 99 00 00
01 00 00 00
00 CA 9A 3B 00 00 00 00
80 F0 FA 02 00 00 00 00
00 E1 F5 05 00 00 00 00
E0 E0 7D 57

EE 01 00 00
01
A1 98 00 00
01 00 00 00
00 CA 9A 3B 00 00 00 00
80 F0 FA 02 00 00 00 00
00 E1 F5 05 00 00 00 00
44 D6 7E 57

04 02 00 00
01
6D 99 00 00
01 00 00 00
00 78 41 CB 02 00 00 00
00 46 C3 23 00 00 00 00
00 8C 86 47 00 00 00 00
E8 4E 80 57

05 02 00 00
01
9B 98 00 00
01 00 00 00
00 CA 9A 3B 00 00 00 00
80 F0 FA 02 00 00 00 00
00 E1 F5 05 00 00 00 00
AC 03 80 57

07 02 00 00
01
A1 98 00 00
01 00 00 00
00 CA 9A 3B 00 00 00 00
80 F0 FA 02 00 00 00 00
00 E1 F5 05 00 00 00 00
C8 23 80 57

08 02 00 00
01
16 99 00 00
01 00 00 00
00 CA 9A 3B 00 00 00 00
80 F0 FA 02 00 00 00 00
00 E1 F5 05 00 00 00 00
10 09 80 57

FB 01 00 00
02
40 99 00 00
01 00 00 00
01 CA 9A 3B 00 00 00 00
80 F0 FA 02 00 00 00 00
00 E1 F5 05 00 00 00 00
F8 2F 80 57

FC 01 00 00
02
43 99 00 00
01 00 00 00
01 CA 9A 3B 00 00 00 00
80 F0 FA 02 00 00 00 00
00 E1 F5 05 00 00 00 00
F8 2F 80 57

FE 01 00 00
02
40 99 00 00
01 00 00 00
01 CA 9A 3B 00 00 00 00
80 F0 FA 02 00 00 00 00
00 E1 F5 05 00 00 00 00
F8 2F 80 57

F1 01 00 00
02
5F 0E 00 00
E8 03 00 00
00 65 CD 1D 00 00 00 00
40 78 7D 01 00 00 00 00
80 F0 FA 02 00 00 00 00
88 EC 7E 5

**Comment by DummkopfOfHachtenduden** [comment]
Mh, you are right checked that again. I shouldn't rely so much on database layout :smile: 
`TidGroupID` seemed much more reasonable as it's used in 
`0x7508 - CLIENT_AGENT_CONSIGNMENT_REGISTER_REQUEST` and quantity being an ushort most time with exception Gold in some places.
