### ISSUE TITLE
Broken link in JMXPACK

### ISSUE THREAD

**Issue by mahmoudfarouq** [DummkopfOfHachtenduden/SilkroadDoc#9]
Hey, I was looking for the PK2 format, i found this link, http://www.stealthex.org/site/showthread.php?5440-More-about-PK2-Internals, in the https://github.com/DummkopfOfHachtenduden/SilkroadDoc/wiki/JMXPACK page,

The link is broken so can you please provide any alternate link or anything that describes the format in detail?

**Comment by DummkopfOfHachtenduden** [comment]
stealthhex.org went down and archive.org has no backup of the page. It's probably lost forever.
